method: texnet
inherit_from: configs/GAN/000.yaml
data:
  with_shuffle: False
training:
  vis_fixviews: True
generation:
  batch_size: 1
test:
  model_file: model.pt
  vis_dir: 'out/GAN/car/eval_fix'
  dataset_split: 'test_vis' 
  with_occnet: False
  generation_mode: 'gan'