method: texnet
inherit_from: configs/singleview/texfields/car.yaml
data:
  path_shapes: data/demo
  dataset_imgs_type: image_folder
  img_size: 256
model:
  model_url: 'https://s3.eu-central-1.amazonaws.com/avg-projects/texture_fields/models/car-b3b2a506.pt'
generation:
  batch_size: 1
test:
  model_file: model_best.pt
  vis_dir: 'out/demo'
  dataset_split: 'test_vis' 
  with_occnet: False
  generation_mode: 'HD'